services:
  studentgrades:
    build: studentgrades
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://student_grades:3306/student_follow_up
      DB_USER_NAME: root
      DB_PASSWORD: IchLerne1*++
    restart: always
    depends_on:
      student_grades:
          condition: service_healthy
  student_grades:
    image: mysql:8.0.38 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: IchLerne1*++
      MYSQL_DATABASE: student_follow_up
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10